language: node_js
node_js:
  - "node"
script:
  - "npm start"
# Used to push a build to the `site` branch on GitHub
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: .deploy_git
  target_branch: site
  on:
    branch: master
